### ISSUE TITLE
WYSIWYG for @font-your-face

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/fontyourface#1]
I am getting this message for the WYSIWYG sub-module.

"This version is not compatible with Backdrop CMS 1.x."

Is this sub-module likely to be made compatible in the future or should we remove it from the project until/unless it gets fixed in the future. 

At a minimum, maybe add some comments to readme file, because I always find it confusing about why I have a module in my module directory that is not compatible with Backdrop. 

![font-your-face](https://user-images.githubusercontent.com/3144571/129091864-48102ba6-1113-4032-8656-7788b8d2b3b5.png)

**Comment by yorkshire-pudding** [comment]
I agree. Better to remove than have this which could cause confusion
