### ISSUE TITLE
Error: The list of Google Fonts could not be fetched.

### ISSUE THREAD

**Issue by leeksoup** [backdrop-contrib/fontyourface#2]
I just installed and enabled the @font-your-face module and I get the error:

> The list of Google Fonts could not be fetched. Verify that your server can connect the Google Servers (https://www.googleapis.com). Error: Forbidden

Is there something further I need to configure? I found an issue about this on the Drupal site: https://www.drupal.org/project/fontyourface/issues/3183601

If this is the same issue, then how do I set the API key to the right value? No config option came up for that when I installed.

**Comment by leeksoup** [comment]
I brought it up on a Drupal 8 site. Here is a screenshot of admin/appearance/font/settings:
![image](https://github.com/backdrop-contrib/fontyourface/assets/25186767/88d0cb8d-5ec1-433d-961c-3a5d17d9d561)

The only settings I can find on the Backdrop site are at admin/config/user-interface/fontyourface. There is a similar button to "import google fonts" but no field to enter an API Key. Backdrop screenshot:
![image](https://github.com/backdrop-contrib/fontyourface/assets/25186767/343592e8-eb8b-4110-9bad-eb2c4f07e6c5)

ETA: Backdrop screenshot and clarify Drupal version.

**Comment by leeksoup** [comment]
@herbdool - I have fixed the above issue on my local dev copy of the module and tested it on my dev / test sites. Screenshot:

![image](https://github.com/backdrop-contrib/fontyourface/assets/25186767/cac7034b-de74-490b-9a8f-bfa54b81e11a)

**Comment by herbdool** [comment]
Hi @leeksoup, thanks for reporting this. If you'd like, please fork this repository by going to https://github.com/backdrop-contrib/fontyourface and clicking on fork. Then edit your fork and save. Then it'll probably show a button for making a PR (pull request) this will allow you to share it back to the main project so I can see and merge it if it works. Thanks

**Comment by leeksoup** [comment]
@herbdool - done.
